// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/discernhq/devx/pkg/appcontext"
	"github.com/discernhq/devx/pkg/config"
	"github.com/discernhq/devx/pkg/workspace"
)

// Injectors from wire.go:

func InitCLI() (RootCmd, error) {
	context := appcontext.Context()
	workspaceConfig, err := workspace.NewWorkspaceConfig()
	if err != nil {
		return RootCmd{}, err
	}
	fileStore, err := workspace.NewFileStore(context, workspaceConfig)
	if err != nil {
		return RootCmd{}, err
	}
	newConfigGetCmdParams := NewConfigGetCmdParams{
		Store: fileStore,
	}
	configGetCmd := NewConfigGetCmd(newConfigGetCmdParams)
	configStoreSettings := workspaceConfig.ConfigStore
	newConfigSetCmdParams := NewConfigSetCmdParams{
		Store:    fileStore,
		Settings: configStoreSettings,
	}
	configSetCmd := NewConfigSetCmd(newConfigSetCmdParams)
	workspaceConfigStoreSettings := &workspaceConfig.ConfigStore
	encryptedFileEditor := config.NewEncryptedFileEditor(fileStore)
	newConfigEditCmdParams := NewConfigEditCmdParams{
		ConfigStoreSettings: workspaceConfigStoreSettings,
		EncryptedFileEditor: encryptedFileEditor,
	}
	configEditCmd := NewConfigEditCmd(newConfigEditCmdParams)
	configCmdParams := ConfigCmdParams{
		ConfigGetCmd:  configGetCmd,
		ConfigSetCmd:  configSetCmd,
		ConfigEditCmd: configEditCmd,
	}
	configCmd := NewConfigCmd(configCmdParams)
	buildCmd := NewBuildCmd()
	rootCommandParams := RootCommandParams{
		ConfigCmd: configCmd,
		BuildCmd:  buildCmd,
	}
	rootCmd := NewRootCmd(rootCommandParams)
	return rootCmd, nil
}
