package modspecv2

import (
	"fmt"
	"github.com/dave/jennifer/jen"
	"go/types"
	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/packages"
	"os"
	"path/filepath"
	"strings"
)

// SaveArtifacts saves the artifacts to disk relative to the module directory
func SaveArtifacts(module *packages.Module, artifacts []Artifact) ([]string, error) {
	var outFiles []string
	for _, artifact := range artifacts {
		outfile, err := saveArtifact(module.Dir, artifact)
		if err != nil {
			return outFiles, err
		}

		outFiles = append(outFiles, outfile)
	}
	return outFiles, nil
}

func GenGoExt(name string) string {
	return fmt.Sprintf("%s.gen.go", name)
}

func saveArtifact(moduleRoot string, artifact Artifact) (string, error) {
	filename := filepath.Join(moduleRoot, artifact.OutputPath())
	outDir := filepath.Dir(filename)
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return "", err
	}

	file, err := os.OpenFile(filename, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		return "", err
	}
	defer func(file *os.File) {
		_ = file.Close()
	}(file)

	return filename, artifact.File().Render(file)
}

func RelPathFromPass(pass *analysis.Pass) string {
	return strings.Replace(pass.Pkg.Path(), pass.Module.Path, "", 1)
}

func NewJenFileFromPackage(pkg *types.Package) *jen.File {
	f := jen.NewFilePath(pkg.Path())
	f.HeaderComment("Code generated by kibu. DO NOT EDIT.")
	return f
}

func GatherResults[T any](results []*analysis.Pass) (resultsMap []T) {
	for _, pass := range results {
		for _, result := range pass.ResultOf {
			if result, ok := result.(T); ok {
				resultsMap = append(resultsMap, result)
			}
		}
	}
	return
}
