package kibugenv2

import (
	"fmt"
	"github.com/dave/jennifer/jen"
	"github.com/samber/lo"
)

func WithGenExt(name string) string {
	return fmt.Sprintf("%s.gen.go",
		lo.SnakeCase(name),
	)
}

func generatePlumbing(params *GenParams) error {
	for _, _ = range params.Pkg.Services {
		f := jen.NewFilePath(params.Pkg.GoPkg.Path())
		f.HeaderComment("Code generated by kibugenv2. DO NOT EDIT.")
		//f.Var().Id(svc.Name).Op("*").Id(svc.Name).Tag(map[xstring]string{
		//	"wire": "-",
		//})
		params.Artifact.Files = append(params.Artifact.Files, f)
	}
	return nil
}
